### ISSUE TITLE
Add new sections dynamically

### ISSUE THREAD

**Issue by haifengkao** [apploft/APLExpandableCollectionView#4]
I got the same issue of #3 . why is it closed?

**Comment by michaelkamphausen** [comment]
I have no idea why it was closed.

This component was developed with a static number of sections and items in mind, so I haven't tested it with a dynamically changing number of sections or items.
Feel free to add this feature , you're welcome to send a pull request!

**Comment by michaelkamphausen** [comment]
@stellz has developed and contributed this feature and a new pod version is available. Have a look at `[self.collectionView addExpandedSection:NO];` and the sample app implementation.

**Comment by haifengkao** [comment]
thx
