### ISSUE TITLE
Cannot init from code

### ISSUE THREAD

**Issue by hyouuu** [apploft/APLExpandableCollectionView#8]
Hello! Thanks for sharing this! We should add a simple init method to support initing from code:

- (instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout *)layout {
  self = [super initWithFrame:frame collectionViewLayout:layout];
  if (self) {
    [self commonInit];
  }
  return self;
}

**Comment by michaelkamphausen** [comment]
Hi!
You are right. The APLExpandableCollectionView has an initWithFrame: implementation, but this method is not the designated initializer for a UICollectionView as you mentioned above. So I will replace with initWithFrame:collectionViewLayout:.

**Comment by hyouuu** [comment]
Awesome - keep up the good work and look forward to updates :+1:
