### ISSUE TITLE
Would be great if we could customize section separators and item separators

### ISSUE THREAD

**Issue by hyouuu** [apploft/APLExpandableCollectionView#9]
The expandable collection view uses first item in each section as the "header" and the rest as "items", and it'd be very useful if we could customize the separators for inter-section as well as inter-item (or is there an easy way to do that?)

PS: The response to the previous issue was super fast :+1:

**Comment by michaelkamphausen** [comment]
UICollectionView already supports custom separators with decoration views. You'll need to subclass APLExpandableSectionFlowLayout for your customized layout and UICollectionReusableView for your decoration views. See Apple's documentation:
https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/CreatingCustomLayouts/CreatingCustomLayouts.html#//apple_ref/doc/uid/TP40012334-CH5-SW12

**Comment by hyouuu** [comment]
Indeed we can do customizations. My point is that since it'd be very common for expandable collections to have some sort of separators, providing a template within this component would be really helpful. Just a suggestion though :)

**Comment by michaelkamphausen** [comment]
Those developers who need decoration views, presumably need them in quite different manners. I'd prefer to keep the layout flexibility and customizability Apple provides and concentrate on the expandable feature for this cocoapod. "Do one thing and do it well." :wink:
But feel free to fork and extend this project or write a dependent pod for your use case!

**Comment by hyouuu** [comment]
Totally - thanks again for sharing this!
